<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RajaongkirCitySeeder extends Seeder
{
    public function run(): void
    {
        // Data kota/kabupaten Indonesia — sudah kompatibel dengan Binderbyte API
        // Binderbyte menerima nama kota dalam huruf kecil
        $cities = [
            // ACEH
            ['city_name' => 'Banda Aceh', 'province' => 'Aceh'],
            ['city_name' => 'Sabang', 'province' => 'Aceh'],
            ['city_name' => 'Langsa', 'province' => 'Aceh'],
            ['city_name' => 'Lhokseumawe', 'province' => 'Aceh'],
            ['city_name' => 'Subulussalam', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Barat', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Besar', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Selatan', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Tengah', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Timur', 'province' => 'Aceh'],
            ['city_name' => 'Aceh Utara', 'province' => 'Aceh'],
            ['city_name' => 'Bireuen', 'province' => 'Aceh'],
            ['city_name' => 'Pidie', 'province' => 'Aceh'],
            ['city_name' => 'Simeulue', 'province' => 'Aceh'],
            // SUMATERA UTARA
            ['city_name' => 'Medan', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Binjai', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Pematangsiantar', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Tebing Tinggi', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Tanjungbalai', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Padangsidimpuan', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Gunungsitoli', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Deli Serdang', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Langkat', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Karo', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Simalungun', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Asahan', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Labuhanbatu', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Tapanuli Selatan', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Tapanuli Tengah', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Tapanuli Utara', 'province' => 'Sumatera Utara'],
            ['city_name' => 'Nias', 'province' => 'Sumatera Utara'],
            // SUMATERA BARAT
            ['city_name' => 'Padang', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Bukittinggi', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Payakumbuh', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Padangpanjang', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Sawahlunto', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Solok', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Pariaman', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Agam', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Pasaman', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Sijunjung', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Tanah Datar', 'province' => 'Sumatera Barat'],
            ['city_name' => 'Pesisir Selatan', 'province' => 'Sumatera Barat'],
            // RIAU
            ['city_name' => 'Pekanbaru', 'province' => 'Riau'],
            ['city_name' => 'Dumai', 'province' => 'Riau'],
            ['city_name' => 'Bengkalis', 'province' => 'Riau'],
            ['city_name' => 'Indragiri Hilir', 'province' => 'Riau'],
            ['city_name' => 'Indragiri Hulu', 'province' => 'Riau'],
            ['city_name' => 'Kampar', 'province' => 'Riau'],
            ['city_name' => 'Kuantan Singingi', 'province' => 'Riau'],
            ['city_name' => 'Pelalawan', 'province' => 'Riau'],
            ['city_name' => 'Rokan Hilir', 'province' => 'Riau'],
            ['city_name' => 'Rokan Hulu', 'province' => 'Riau'],
            ['city_name' => 'Siak', 'province' => 'Riau'],
            // KEPULAUAN RIAU
            ['city_name' => 'Batam', 'province' => 'Kepulauan Riau'],
            ['city_name' => 'Tanjung Pinang', 'province' => 'Kepulauan Riau'],
            ['city_name' => 'Bintan', 'province' => 'Kepulauan Riau'],
            ['city_name' => 'Karimun', 'province' => 'Kepulauan Riau'],
            ['city_name' => 'Natuna', 'province' => 'Kepulauan Riau'],
            ['city_name' => 'Lingga', 'province' => 'Kepulauan Riau'],
            // JAMBI
            ['city_name' => 'Jambi', 'province' => 'Jambi'],
            ['city_name' => 'Sungai Penuh', 'province' => 'Jambi'],
            ['city_name' => 'Batanghari', 'province' => 'Jambi'],
            ['city_name' => 'Bungo', 'province' => 'Jambi'],
            ['city_name' => 'Kerinci', 'province' => 'Jambi'],
            ['city_name' => 'Merangin', 'province' => 'Jambi'],
            ['city_name' => 'Muaro Jambi', 'province' => 'Jambi'],
            ['city_name' => 'Sarolangun', 'province' => 'Jambi'],
            ['city_name' => 'Tanjung Jabung Barat', 'province' => 'Jambi'],
            ['city_name' => 'Tanjung Jabung Timur', 'province' => 'Jambi'],
            ['city_name' => 'Tebo', 'province' => 'Jambi'],
            // SUMATERA SELATAN
            ['city_name' => 'Palembang', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Lubuklinggau', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Pagar Alam', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Prabumulih', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Banyuasin', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Empat Lawang', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Lahat', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Muara Enim', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Musi Banyuasin', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Musi Rawas', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Ogan Ilir', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Ogan Komering Ilir', 'province' => 'Sumatera Selatan'],
            ['city_name' => 'Ogan Komering Ulu', 'province' => 'Sumatera Selatan'],
            // BENGKULU
            ['city_name' => 'Bengkulu', 'province' => 'Bengkulu'],
            ['city_name' => 'Bengkulu Selatan', 'province' => 'Bengkulu'],
            ['city_name' => 'Bengkulu Tengah', 'province' => 'Bengkulu'],
            ['city_name' => 'Bengkulu Utara', 'province' => 'Bengkulu'],
            ['city_name' => 'Kaur', 'province' => 'Bengkulu'],
            ['city_name' => 'Kepahiang', 'province' => 'Bengkulu'],
            ['city_name' => 'Lebong', 'province' => 'Bengkulu'],
            ['city_name' => 'Mukomuko', 'province' => 'Bengkulu'],
            ['city_name' => 'Rejang Lebong', 'province' => 'Bengkulu'],
            // LAMPUNG
            ['city_name' => 'Bandar Lampung', 'province' => 'Lampung'],
            ['city_name' => 'Metro', 'province' => 'Lampung'],
            ['city_name' => 'Lampung Barat', 'province' => 'Lampung'],
            ['city_name' => 'Lampung Selatan', 'province' => 'Lampung'],
            ['city_name' => 'Lampung Tengah', 'province' => 'Lampung'],
            ['city_name' => 'Lampung Timur', 'province' => 'Lampung'],
            ['city_name' => 'Lampung Utara', 'province' => 'Lampung'],
            ['city_name' => 'Mesuji', 'province' => 'Lampung'],
            ['city_name' => 'Pesawaran', 'province' => 'Lampung'],
            ['city_name' => 'Pringsewu', 'province' => 'Lampung'],
            ['city_name' => 'Tanggamus', 'province' => 'Lampung'],
            ['city_name' => 'Tulang Bawang', 'province' => 'Lampung'],
            ['city_name' => 'Way Kanan', 'province' => 'Lampung'],
            // BANGKA BELITUNG
            ['city_name' => 'Pangkal Pinang', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Bangka', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Bangka Barat', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Bangka Selatan', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Bangka Tengah', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Belitung', 'province' => 'Bangka Belitung'],
            ['city_name' => 'Belitung Timur', 'province' => 'Bangka Belitung'],
            // DKI JAKARTA
            ['city_name' => 'Jakarta Pusat', 'province' => 'DKI Jakarta'],
            ['city_name' => 'Jakarta Utara', 'province' => 'DKI Jakarta'],
            ['city_name' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
            ['city_name' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
            ['city_name' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
            ['city_name' => 'Kepulauan Seribu', 'province' => 'DKI Jakarta'],
            // BANTEN
            ['city_name' => 'Serang', 'province' => 'Banten'],
            ['city_name' => 'Cilegon', 'province' => 'Banten'],
            ['city_name' => 'Tangerang', 'province' => 'Banten'],
            ['city_name' => 'Tangerang Selatan', 'province' => 'Banten'],
            ['city_name' => 'Lebak', 'province' => 'Banten'],
            ['city_name' => 'Pandeglang', 'province' => 'Banten'],
            ['city_name' => 'Tangerang Kabupaten', 'province' => 'Banten'],
            // JAWA BARAT
            ['city_name' => 'Bandung', 'province' => 'Jawa Barat'],
            ['city_name' => 'Bogor', 'province' => 'Jawa Barat'],
            ['city_name' => 'Bekasi', 'province' => 'Jawa Barat'],
            ['city_name' => 'Depok', 'province' => 'Jawa Barat'],
            ['city_name' => 'Cimahi', 'province' => 'Jawa Barat'],
            ['city_name' => 'Cirebon', 'province' => 'Jawa Barat'],
            ['city_name' => 'Sukabumi', 'province' => 'Jawa Barat'],
            ['city_name' => 'Tasikmalaya', 'province' => 'Jawa Barat'],
            ['city_name' => 'Banjar', 'province' => 'Jawa Barat'],
            ['city_name' => 'Ciamis', 'province' => 'Jawa Barat'],
            ['city_name' => 'Cianjur', 'province' => 'Jawa Barat'],
            ['city_name' => 'Garut', 'province' => 'Jawa Barat'],
            ['city_name' => 'Indramayu', 'province' => 'Jawa Barat'],
            ['city_name' => 'Karawang', 'province' => 'Jawa Barat'],
            ['city_name' => 'Kuningan', 'province' => 'Jawa Barat'],
            ['city_name' => 'Majalengka', 'province' => 'Jawa Barat'],
            ['city_name' => 'Purwakarta', 'province' => 'Jawa Barat'],
            ['city_name' => 'Subang', 'province' => 'Jawa Barat'],
            ['city_name' => 'Sumedang', 'province' => 'Jawa Barat'],
            // JAWA TENGAH
            ['city_name' => 'Semarang', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Solo', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Magelang', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Salatiga', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Pekalongan', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Tegal', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Purwokerto', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Banjarnegara', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Banyumas', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Batang', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Blora', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Boyolali', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Brebes', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Cilacap', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Demak', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Grobogan', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Jepara', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Karanganyar', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Kebumen', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Kendal', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Klaten', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Kudus', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Magelang Kabupaten', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Pati', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Pemalang', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Purbalingga', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Purworejo', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Rembang', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Sragen', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Sukoharjo', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Tegal Kabupaten', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Temanggung', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Wonogiri', 'province' => 'Jawa Tengah'],
            ['city_name' => 'Wonosobo', 'province' => 'Jawa Tengah'],
            // DI YOGYAKARTA
            ['city_name' => 'Yogyakarta', 'province' => 'DI Yogyakarta'],
            ['city_name' => 'Bantul', 'province' => 'DI Yogyakarta'],
            ['city_name' => 'Gunung Kidul', 'province' => 'DI Yogyakarta'],
            ['city_name' => 'Kulon Progo', 'province' => 'DI Yogyakarta'],
            ['city_name' => 'Sleman', 'province' => 'DI Yogyakarta'],
            // JAWA TIMUR
            ['city_name' => 'Surabaya', 'province' => 'Jawa Timur'],
            ['city_name' => 'Malang', 'province' => 'Jawa Timur'],
            ['city_name' => 'Kediri', 'province' => 'Jawa Timur'],
            ['city_name' => 'Blitar', 'province' => 'Jawa Timur'],
            ['city_name' => 'Madiun', 'province' => 'Jawa Timur'],
            ['city_name' => 'Mojokerto', 'province' => 'Jawa Timur'],
            ['city_name' => 'Pasuruan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Probolinggo', 'province' => 'Jawa Timur'],
            ['city_name' => 'Batu', 'province' => 'Jawa Timur'],
            ['city_name' => 'Bangkalan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Banyuwangi', 'province' => 'Jawa Timur'],
            ['city_name' => 'Bojonegoro', 'province' => 'Jawa Timur'],
            ['city_name' => 'Bondowoso', 'province' => 'Jawa Timur'],
            ['city_name' => 'Gresik', 'province' => 'Jawa Timur'],
            ['city_name' => 'Jember', 'province' => 'Jawa Timur'],
            ['city_name' => 'Jombang', 'province' => 'Jawa Timur'],
            ['city_name' => 'Lamongan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Lumajang', 'province' => 'Jawa Timur'],
            ['city_name' => 'Magetan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Nganjuk', 'province' => 'Jawa Timur'],
            ['city_name' => 'Ngawi', 'province' => 'Jawa Timur'],
            ['city_name' => 'Pacitan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Pamekasan', 'province' => 'Jawa Timur'],
            ['city_name' => 'Ponorogo', 'province' => 'Jawa Timur'],
            ['city_name' => 'Sampang', 'province' => 'Jawa Timur'],
            ['city_name' => 'Sidoarjo', 'province' => 'Jawa Timur'],
            ['city_name' => 'Situbondo', 'province' => 'Jawa Timur'],
            ['city_name' => 'Sumenep', 'province' => 'Jawa Timur'],
            ['city_name' => 'Trenggalek', 'province' => 'Jawa Timur'],
            ['city_name' => 'Tuban', 'province' => 'Jawa Timur'],
            ['city_name' => 'Tulungagung', 'province' => 'Jawa Timur'],
            // BALI
            ['city_name' => 'Denpasar', 'province' => 'Bali'],
            ['city_name' => 'Badung', 'province' => 'Bali'],
            ['city_name' => 'Bangli', 'province' => 'Bali'],
            ['city_name' => 'Buleleng', 'province' => 'Bali'],
            ['city_name' => 'Gianyar', 'province' => 'Bali'],
            ['city_name' => 'Jembrana', 'province' => 'Bali'],
            ['city_name' => 'Karangasem', 'province' => 'Bali'],
            ['city_name' => 'Klungkung', 'province' => 'Bali'],
            ['city_name' => 'Tabanan', 'province' => 'Bali'],
            // NTB
            ['city_name' => 'Mataram', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Bima', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Dompu', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Lombok Barat', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Lombok Tengah', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Lombok Timur', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Lombok Utara', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Sumbawa', 'province' => 'Nusa Tenggara Barat'],
            ['city_name' => 'Sumbawa Barat', 'province' => 'Nusa Tenggara Barat'],
            // NTT
            ['city_name' => 'Kupang', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Ende', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Flores Timur', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Manggarai', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Manggarai Barat', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Ngada', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Sikka', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Sumba Barat', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Sumba Timur', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Timor Tengah Selatan', 'province' => 'Nusa Tenggara Timur'],
            ['city_name' => 'Timor Tengah Utara', 'province' => 'Nusa Tenggara Timur'],
            // KALIMANTAN BARAT
            ['city_name' => 'Pontianak', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Singkawang', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Kapuas Hulu', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Ketapang', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Kubu Raya', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Landak', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Melawi', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Sambas', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Sanggau', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Sekadau', 'province' => 'Kalimantan Barat'],
            ['city_name' => 'Sintang', 'province' => 'Kalimantan Barat'],
            // KALIMANTAN TENGAH
            ['city_name' => 'Palangka Raya', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Barito Selatan', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Barito Timur', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Barito Utara', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Gunung Mas', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Kapuas', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Katingan', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Kotawaringin Barat', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Kotawaringin Timur', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Lamandau', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Murung Raya', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Pulang Pisau', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Seruyan', 'province' => 'Kalimantan Tengah'],
            ['city_name' => 'Sukamara', 'province' => 'Kalimantan Tengah'],
            // KALIMANTAN SELATAN
            ['city_name' => 'Banjarmasin', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Banjarbaru', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Balangan', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Banjar', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Barito Kuala', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Hulu Sungai Selatan', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Hulu Sungai Tengah', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Hulu Sungai Utara', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Kotabaru', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Tabalong', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Tanah Bumbu', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Tanah Laut', 'province' => 'Kalimantan Selatan'],
            ['city_name' => 'Tapin', 'province' => 'Kalimantan Selatan'],
            // KALIMANTAN TIMUR
            ['city_name' => 'Samarinda', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Balikpapan', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Bontang', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Berau', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Kutai Barat', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Kutai Kartanegara', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Kutai Timur', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Mahakam Ulu', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Paser', 'province' => 'Kalimantan Timur'],
            ['city_name' => 'Penajam Paser Utara', 'province' => 'Kalimantan Timur'],
            // KALIMANTAN UTARA
            ['city_name' => 'Tarakan', 'province' => 'Kalimantan Utara'],
            ['city_name' => 'Bulungan', 'province' => 'Kalimantan Utara'],
            ['city_name' => 'Malinau', 'province' => 'Kalimantan Utara'],
            ['city_name' => 'Nunukan', 'province' => 'Kalimantan Utara'],
            ['city_name' => 'Tana Tidung', 'province' => 'Kalimantan Utara'],
            // SULAWESI UTARA
            ['city_name' => 'Manado', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Bitung', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Kotamobagu', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Tomohon', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Bolaang Mongondow', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Kepulauan Sangihe', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Kepulauan Talaud', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Minahasa', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Minahasa Selatan', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Minahasa Tenggara', 'province' => 'Sulawesi Utara'],
            ['city_name' => 'Minahasa Utara', 'province' => 'Sulawesi Utara'],
            // SULAWESI TENGAH
            ['city_name' => 'Palu', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Banggai', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Buol', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Donggala', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Morowali', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Parigi Moutong', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Poso', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Sigi', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Tojo Una-Una', 'province' => 'Sulawesi Tengah'],
            ['city_name' => 'Toli-Toli', 'province' => 'Sulawesi Tengah'],
            // SULAWESI SELATAN
            ['city_name' => 'Makassar', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Palopo', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Pare-Pare', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Bantaeng', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Barru', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Bone', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Bulukumba', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Enrekang', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Gowa', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Jeneponto', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Kepulauan Selayar', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Luwu', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Luwu Timur', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Luwu Utara', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Maros', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Pangkajene Kepulauan', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Pinrang', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Sidenreng Rappang', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Sinjai', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Soppeng', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Takalar', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Tana Toraja', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Toraja Utara', 'province' => 'Sulawesi Selatan'],
            ['city_name' => 'Wajo', 'province' => 'Sulawesi Selatan'],
            // SULAWESI TENGGARA
            ['city_name' => 'Kendari', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Bau-Bau', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Bombana', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Buton', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Kolaka', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Kolaka Utara', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Konawe', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Konawe Selatan', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Konawe Utara', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Muna', 'province' => 'Sulawesi Tenggara'],
            ['city_name' => 'Wakatobi', 'province' => 'Sulawesi Tenggara'],
            // GORONTALO
            ['city_name' => 'Gorontalo', 'province' => 'Gorontalo'],
            ['city_name' => 'Boalemo', 'province' => 'Gorontalo'],
            ['city_name' => 'Bone Bolango', 'province' => 'Gorontalo'],
            ['city_name' => 'Gorontalo Utara', 'province' => 'Gorontalo'],
            ['city_name' => 'Pahuwato', 'province' => 'Gorontalo'],
            // SULAWESI BARAT
            ['city_name' => 'Mamuju', 'province' => 'Sulawesi Barat'],
            ['city_name' => 'Majene', 'province' => 'Sulawesi Barat'],
            ['city_name' => 'Mamasa', 'province' => 'Sulawesi Barat'],
            ['city_name' => 'Mamuju Tengah', 'province' => 'Sulawesi Barat'],
            ['city_name' => 'Mamuju Utara', 'province' => 'Sulawesi Barat'],
            ['city_name' => 'Polewali Mandar', 'province' => 'Sulawesi Barat'],
            // MALUKU
            ['city_name' => 'Ambon', 'province' => 'Maluku'],
            ['city_name' => 'Tual', 'province' => 'Maluku'],
            ['city_name' => 'Buru', 'province' => 'Maluku'],
            ['city_name' => 'Buru Selatan', 'province' => 'Maluku'],
            ['city_name' => 'Kepulauan Aru', 'province' => 'Maluku'],
            ['city_name' => 'Maluku Barat Daya', 'province' => 'Maluku'],
            ['city_name' => 'Maluku Tengah', 'province' => 'Maluku'],
            ['city_name' => 'Maluku Tenggara', 'province' => 'Maluku'],
            ['city_name' => 'Seram Bagian Barat', 'province' => 'Maluku'],
            ['city_name' => 'Seram Bagian Timur', 'province' => 'Maluku'],
            // MALUKU UTARA
            ['city_name' => 'Ternate', 'province' => 'Maluku Utara'],
            ['city_name' => 'Tidore Kepulauan', 'province' => 'Maluku Utara'],
            ['city_name' => 'Halmahera Barat', 'province' => 'Maluku Utara'],
            ['city_name' => 'Halmahera Selatan', 'province' => 'Maluku Utara'],
            ['city_name' => 'Halmahera Tengah', 'province' => 'Maluku Utara'],
            ['city_name' => 'Halmahera Timur', 'province' => 'Maluku Utara'],
            ['city_name' => 'Halmahera Utara', 'province' => 'Maluku Utara'],
            ['city_name' => 'Kepulauan Sula', 'province' => 'Maluku Utara'],
            // PAPUA BARAT
            ['city_name' => 'Manokwari', 'province' => 'Papua Barat'],
            ['city_name' => 'Sorong', 'province' => 'Papua Barat'],
            ['city_name' => 'Fakfak', 'province' => 'Papua Barat'],
            ['city_name' => 'Kaimana', 'province' => 'Papua Barat'],
            ['city_name' => 'Manokwari Selatan', 'province' => 'Papua Barat'],
            ['city_name' => 'Maybrat', 'province' => 'Papua Barat'],
            ['city_name' => 'Raja Ampat', 'province' => 'Papua Barat'],
            ['city_name' => 'Sorong Selatan', 'province' => 'Papua Barat'],
            ['city_name' => 'Tambrauw', 'province' => 'Papua Barat'],
            ['city_name' => 'Teluk Bintuni', 'province' => 'Papua Barat'],
            ['city_name' => 'Teluk Wondama', 'province' => 'Papua Barat'],
            // PAPUA
            ['city_name' => 'Jayapura', 'province' => 'Papua'],
            ['city_name' => 'Asmat', 'province' => 'Papua'],
            ['city_name' => 'Biak Numfor', 'province' => 'Papua'],
            ['city_name' => 'Boven Digoel', 'province' => 'Papua'],
            ['city_name' => 'Deiyai', 'province' => 'Papua'],
            ['city_name' => 'Dogiyai', 'province' => 'Papua'],
            ['city_name' => 'Intan Jaya', 'province' => 'Papua'],
            ['city_name' => 'Keerom', 'province' => 'Papua'],
            ['city_name' => 'Kepulauan Yapen', 'province' => 'Papua'],
            ['city_name' => 'Lanny Jaya', 'province' => 'Papua'],
            ['city_name' => 'Mamberamo Raya', 'province' => 'Papua'],
            ['city_name' => 'Mappi', 'province' => 'Papua'],
            ['city_name' => 'Merauke', 'province' => 'Papua'],
            ['city_name' => 'Mimika', 'province' => 'Papua'],
            ['city_name' => 'Nabire', 'province' => 'Papua'],
            ['city_name' => 'Nduga', 'province' => 'Papua'],
            ['city_name' => 'Paniai', 'province' => 'Papua'],
            ['city_name' => 'Pegunungan Bintang', 'province' => 'Papua'],
            ['city_name' => 'Puncak', 'province' => 'Papua'],
            ['city_name' => 'Sarmi', 'province' => 'Papua'],
            ['city_name' => 'Supiori', 'province' => 'Papua'],
            ['city_name' => 'Tolikara', 'province' => 'Papua'],
            ['city_name' => 'Waropen', 'province' => 'Papua'],
            ['city_name' => 'Yahukimo', 'province' => 'Papua'],
            ['city_name' => 'Yalimo', 'province' => 'Papua'],
        ];

        $now = now();

        // Refresh data agar sinkron saat dijalankan ulang
        DB::table('rajaongkir_cities')->truncate();
        DB::table('rajaongkir_provinces')->truncate();

        // Bentuk ID stabil dari urutan data agar insertOrIgnore tetap konsisten
        $provinceIds = [];
        $nextProvinceId = 1;
        $rows = [];

        foreach ($cities as $index => $city) {
            $province = $city['province'];

            if (!isset($provinceIds[$province])) {
                $provinceIds[$province] = $nextProvinceId++;
            }

            $rows[] = [
                'city_id' => $index + 1,
                'province_id' => $provinceIds[$province],
                'province' => $province,
                'type' => null,
                'city_name' => $city['city_name'],
                'postal_code' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        // Isi tabel provinsi
        $provinceRows = [];
        foreach ($provinceIds as $provinceName => $provinceId) {
            $provinceRows[] = [
                'province_id' => $provinceId,
                'province' => $provinceName,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('rajaongkir_provinces')->insertOrIgnore($provinceRows);

        // Chunk insert agar cepat
        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('rajaongkir_cities')->insertOrIgnore($chunk);
        }

        $this->command->info('✓ ' . count($cities) . ' kota/kabupaten berhasil di-seed');
    }
}
